version: '3.9'
services:
  frontend:
    container_name: portfolio_frontend
    build: ./front-end
    ports:
      - 3000:3000
    working_dir: /app-frontend
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3000" ]
      timeout: 10s
      retries: 5
  backend:
    container_name: portfolio_backend
    build: ./back-end
    ports:
      - 3001:3001
    working_dir: /app-backend
    command: dev
    volumes:
      - ./back-end:/app-backend
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - JWT_SECRET=jwt_secret
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_HOST=database
      - DB_PORT=3306
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:3001" ]
      timeout: 10s
      retries: 5
  database:
    image: mysql:8.0.23
    container_name: portfolio_database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
